"use strict";

const asse = {
  bgHome: require("./image/bg_splash.png"),
  // bgSignup: require("./image/bg_signup.png"),
  bgSignup: require("./image/sign_up.png"),
  setting: require("./image/settings_selected.png"),
  backWhite: require("./image/back.png"),
  menu: require("./image/menu.png"),
  more: require("../asse/image/more.png"),
  add: require("../asse/image/add.png"),
  logo: require("../asse/image/logo.png"),
  driver: require("../asse/image/driver.png"),
  call_order: require("../asse/image/call_order.png"),
  refresh: require('../asse/image/refresh.png'),
  
  //Eatance
  // bg_login: require("../asse/image/sign_in.png"),
  bg_login: require("../asse/image/bg_login.png"),
  ic_location: require("../asse/image/location.png"),

  rating: require("../asse/image/rateus_selected.png"),
  time: require("../asse/image/time.png"),
  restMenu: require("../asse/image/restaurant_menu.png"),
  address: require("../asse/image/address.png"),
  ic_search: require("../asse/image/search.png"),
  recipe_search: require("../asse/image/recipe_search.png"),
  ic_location_grey: require("../asse/image/location_grey.png"),
  ic_plus: require("../asse/image/plusqty.png"),
  ic_minus: require("../asse/image/minusqty.png"),
  ic_reservation_back: require("../asse/image/ic_back_reservation.png"),
  ic_plus_yellow: require("../asse/image/plus.png"),
  ic_filter: require("../asse/image/filter.png"),
  ic_cart: require("../asse/image/cart.png"),
  ic_up_arrow: require("../asse/image/up_arrow.png"),
  ic_down_arrow: require("../asse/image/down.png"),

  // deselected icons
  home_deselect: require("../asse/image/home_deselected.png"),
  recipe_deselect: require("../asse/image/recipe_deselected.png"),
  order_deselect: require("../asse/image/order_deselected.png"),
  eventbooking_deselect: require("../asse/image/eventbooking_deselected.png"),
  mybooking_deselect: require("../asse/image/mybooking_deselected.png"),
  notification_deselect: require("../asse/image/notification_deselected.png"),
  rateus_deselect: require("../asse/image/rateus_deselected.png"),
  shareus_deselect: require("../asse/image/shareus_deselected.png"),
  privacypolicy_deselect: require("../asse/image/privacypolicy_deselected.png"),
  aboutus_deselect: require("../asse/image/aboutusdeselected.png"),
  contactus_deselect: require("../asse/image/contactus_deselected.png"),
  signout_deselect: require("../asse/image/signout_deselected.png"),

  // selected icons
  home_select: require("../asse/image/home_selected.png"),
  recipe_select: require("../asse/image/recipe_selected.png"),
  order_select: require("../asse/image/order_selected.png"),
  eventbooking_select: require("../asse/image/eventbooking_selected.png"),
  mybooking_select: require("../asse/image/mybooking_selected.png"),
  notification_select: require("../asse/image/notification_selected.png"),
  rateus_select: require("../asse/image/rateus_selected.png"),
  shareus_select: require("../asse/image/shareus_selected.png"),
  privacypolicy_select: require("../asse/image/privacypolicy_selected.png"),
  aboutus_select: require("../asse/image/aboutus_selected.png"),
  contactus_select: require("../asse/image/contactus_selected.png"),
  signout_select: require("../asse/image/signout_selected.png"),

  deliveredselected: require("../asse/image/deliveredselected.png"),
  delivereddeselected: require("../asse/image/delivereddeselected.png"),
  orderplacedselected: require("../asse/image/orderplacedselected.png"),
  onthewayselected: require("../asse/image/onthewayselected.png"),
  onthewaydeselected: require("../asse/image/onthewaydeselected.png"),
  preparingdeselected: require("../asse/image/preparingdeselected.png"),
  preparingselected: require("../asse/image/preparingselected.png"),
  bookingavailable: require("../asse/image/bookingavailable.png"),
  bookingnotavailable: require("../asse/image/bookingnotavailable.png"),
  delete_cart: require("../asse/image/delete.png"),
  ic_close: require("../asse/image/ic_close.png"),
  about_us: require("../asse/image/about_us.png"),
  privacy_policy: require("../asse/image/privacy_policy.png"),
  confirm_background: require("../asse/image/confirm_background.png"),
  confirm_thumb: require("../asse/image/confirm_thumb.png"),
  header_placeholder: require("../asse/image/banner_placeholder.png"),
  delete_White:require("../asse/image/delete_White.png"),
  //profile screen
  call: require("../asse/image/call.png"),
  our_address: require("../asse/image/profile_address.png"),
  name: require("../asse/image/name.png"),
  password: require("../asse/image/password.png"),
  notification: require("../asse/image/notification_selected.png"),
  edit: require("../asse/image/edit_profile.png"),

  rating_white: require("../asse/image/star_white.png"),
  clock_white: require("../asse/image/clock_white.png"),
  star_white: require("../asse/image/star_white.png"),
  people_white: require("../asse/image/people.png"),
  calender_white: require("../asse/image/calendarwhite.png"),
  calender: require("../asse/image/calendar.png"),
  user_placeholder: require("../asse/image/user_placeholder.png"),
  plus_round: require("../asse/image/plus_round.png"),
  minus_round: require("../asse/image/minus_round.png"),
  delete_gray: require("../asse/image/delete_gray.png"),
  tick: require("../asse/image/tick.png"),
  camera_white: require("../asse/image/camera_white.png")
};

export default asse;
